spring:
  mvc:
    path-match:
      matching-strategy: ant_path_matcher

  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: localhost
      username: root
      password: password

  jpa:
    show-sql: true
    hibernate.ddl-auto: update
    properties:
      hibernate:
        format_sql: true
jwt:
  token:
    secret: secret.aa.bb.cc

cloud:
  aws:
    credentials:
      accessKey: ${AWS_ACCESS_KEY_ID}       # AWS IAM AccessKey
      secretKey: ${AWS_SECRET_ACCESS_KEY}   # AWS IAM SecretKey
    s3:
      bucket: mariomarket
    region:
      state: ap-northeast-2
    stack:
      auto: false