spring:
  mvc:
    path-match:
      matching-strategy: ant_path_matcher

  servlet:
    encoding:
      force-response: true
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 20MB

  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/market_db
      username: root
      password: password

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
jwt:
  token:
    secret: secret.aa.bb.cc

cloud:
  aws:
    credentials:
      accessKey: ${AWS_ACCESS_KEY_ID}       # AWS IAM AccessKey
      secretKey: ${AWS_SECRET_ACCESS_KEY}   # AWS IAM SecretKey
    s3:
      bucket: mariomarket
    region:
      state: ap-northeast-2
    stack:
      auto: false